//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvatarItem
    {
        public int id_AI { get; set; }
        public int Item_id { get; set; }
        public int Avatar_id { get; set; }
    
        public virtual Avatars Avatars { get; set; }
        public virtual Item Item { get; set; }
    }
}
