//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class balances
    {
        public int id_balance { get; set; }
        public int Summ { get; set; }
        public int User_id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
