//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battle
    {
        public int id_buttle { get; set; }
        public int AvatarOne { get; set; }
        public int AvatarSecond { get; set; }
        public int result { get; set; }
    
        public virtual Avatars Avatars { get; set; }
        public virtual Avatars Avatars1 { get; set; }
        public virtual Avatars Avatars2 { get; set; }
    }
}
