//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataAddBalance
    {
        public int id_DAB { get; set; }
        public System.DateTime DateIn { get; set; }
        public int AddBall { get; set; }
        public int User_id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
