//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int id_login { get; set; }
        public int User_id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
