//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.ADOApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuberPunckEntities : DbContext
    {
        public CuberPunckEntities()
            : base("name=CuberPunckEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvatarItem> AvatarItem { get; set; }
        public virtual DbSet<Avatars> Avatars { get; set; }
        public virtual DbSet<balances> balances { get; set; }
        public virtual DbSet<Battle> Battle { get; set; }
        public virtual DbSet<DataAddBalance> DataAddBalance { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ListButle> ListButle { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TypeAvatar> TypeAvatar { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
